"""Initial v2.0 schema

Revision ID: a86af6571aac
Revises:
Create Date: 2025-11-18 00:08:39.807601

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a86af6571aac"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "research_status",
            sa.String(length=50),
            nullable=False,
            comment="pending/researching/cached/failed",
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("sources_count", sa.Integer(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=True)
    op.create_table(
        "generation_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider_used",
            sa.String(length=50),
            nullable=False,
            comment="anthropic/google/openai/template",
        ),
        sa.Column("generation_time_ms", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("user_params", sa.JSON(), nullable=False),
        sa.Column("output_files", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_generation_history_artist", "generation_history", ["artist_id"], unique=False
    )
    op.create_index(
        "idx_generation_history_created", "generation_history", ["created_at"], unique=False
    )
    op.create_table(
        "research_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type", sa.String(length=50), nullable=False, comment="paper/article/audio/midi"
        ),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("raw_content", sa.String(), nullable=True),
        sa.Column("extracted_data", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_research_sources_artist_type",
        "research_sources",
        ["artist_id", "source_type"],
        unique=False,
    )
    op.create_table(
        "style_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("text_description", sa.String(), nullable=False),
        sa.Column("quantitative_params", sa.JSON(), nullable=False),
        sa.Column("midi_templates_json", sa.JSON(), nullable=True),
        sa.Column("embedding", Vector(384), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("sources_count", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artist_id"),
    )
    op.create_index(
        "idx_style_profiles_embedding",
        "style_profiles",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_style_profiles_embedding",
        table_name="style_profiles",
        postgresql_using="ivfflat",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("style_profiles")
    op.drop_index("idx_research_sources_artist_type", table_name="research_sources")
    op.drop_table("research_sources")
    op.drop_index("idx_generation_history_created", table_name="generation_history")
    op.drop_index("idx_generation_history_artist", table_name="generation_history")
    op.drop_table("generation_history")
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
